name: Code Check

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            # Setup Action
            - uses: actions/checkout@v3

            # Setup Node
            - uses: actions/setup-node@v3
              with:
                  node-version: 20
                  registry-url: https://npm.github.com/

            # Setup PNPM
            - uses: pnpm/action-setup@v2
              with:
                  version: 8

            # Install Dependencies
            - name: Install dependencies
              run: pnpm install

            # Run Test
            - name: Run test
              run: pnpm run test
