name: Code Check

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            # Setup
            - uses: pnpm/action-setup@v2
              with:
                  version: 8

            # Install Dependencies
            - name: Install dependencies
              run: pnpm install typescript

            # Run Test
            - name: Run test
              run: pnpm run test
